### ISSUE TITLE
6798.15 DEV update languages and services add patch updates

### ISSUE THREAD

**Issue by stephanielingwood** [dry-dock/u16all#1]
https://github.com/Shippable/pm/issues/6798

**Comment by ankul-shippable** [comment]
I think with should add the test script here, so that before going to u16***all images, we should make sure all the services are starting and stopping. We'll need these test scripts in jobRequest to start the service too.

**Comment by stephanielingwood** [comment]
pulled the u16all image and ran the test scripts; all the services were started and stopped successfully. Closing.
