### ISSUE TITLE
10814.1 update cassandra version

### ISSUE THREAD

**Issue by ric03uec** [dry-dock/u16all#104]
- https://github.com/Shippable/pm/issues/10814

### Tasks
- update cassandra version to 3.11

### Tests
- test cassandra is starting/stopping correctly when `drydock/u16all:master` is used as custom image in CI build
- test that user is able to connect to cassandra from build yml

**Comment by Ranjansingh41** [comment]
Build success

https://app.shippable.com/github/Shippable/jobs/u16all_x8664_build/builds/5af43e7abe61c907004f1b42/console

**Comment by Ranjansingh41** [comment]
verified and tested 

https://rcapp.shippable.com/github/Ranjansingh41/couchdb-service-start-test/runs/14/1/console
