### ISSUE TITLE
10814.2 update couchbd version

### ISSUE THREAD

**Issue by Ranjansingh41** [dry-dock/u16all#105]
https://github.com/Shippable/pm/issues/10814
## Tasks

update couchdb version to 3.11

## Tests

1. couchdb is starting/stopping correctly when drydock/u16all:master is used as custom image in CI build
1. test that user is able to connect to couchbd from build yml

**Comment by Ranjansingh41** [comment]
Build success

https://app.shippable.com/github/Shippable/jobs/u16all_x8664_build/builds/5af51e35a55fb8070036b7e9/console

**Comment by Ranjansingh41** [comment]
verified and tested 

https://rcapp.shippable.com/github/Ranjansingh41/couchdb-service-start-test/runs/17/1/console

**Comment by ric03uec** [comment]
looks good, closing
