### ISSUE TITLE
DEV  MVP 4 - Update couchdb version in u16all from 1.6.1 to 2.0.0 

### ISSUE THREAD

**Issue by raksha78** [dry-dock/u16all#31]
FROM https://github.com/Shippable/pm/issues/8613

**Comment by ric03uec** [comment]
@kanthchandra can this be closed ?

**Comment by kanthchandra** [comment]
We couldn't update couchdb in this release. I have spoken to @rageshkrishna about this. We were running into a race condition while installing and it was taking a lot time. So we should do this in the next release v5.8.1.
