### ISSUE TITLE
Update cassandra, couchdb, elasticsearch, memcached and riakversion for v6.4.4

### ISSUE THREAD

**Issue by vijayreddy1991** [dry-dock/u16all#93]
https://github.com/Shippable/pm/issues/10522

| Packages  | Current Version  |Latest Version   | Link for Release Notes   |  
|---|---|---|---|    
| cassandra  |3.11.X  | No update |  https://github.com/apache/cassandra/releases  | 
|  couchdb| 2.1.1  | No updates |http://couchdb.apache.org/ |
| elasticsearch |6.1.1 |  6.2.3 |  https://www.elastic.co/downloads/elasticsearch | 
| memcached |1.5.4  | 1.5.7  |  https://github.com/memcached/memcached/wiki/ReleaseNotes |
|riak |  2.2.3  |   No updates  |   https://github.com/basho/basho_docs/tree/master/content/riak/kv |

**Comment by ric03uec** [comment]
@vijayreddy1991 please update the service versions list before making any changes

**Comment by vijayreddy1991** [comment]
As per your request i updated the versions

**Comment by vijayreddy1991** [comment]
Its failing on the other dependencies once it will fix this issue will be verified.

**Comment by Ranjansingh41** [comment]
https://app.shippable.com/github/Shippable/jobs/x86_64_Ubuntu_16_04_prep/builds/5abcbb344a24a20700a20e7b/console
